version = 1

[[annotations]]
path = ["release-please-config.json", ".release-please-manifest.json", "CHANGELOG.md"]
SPDX-FileCopyrightText = "2026 OpenRail Association AISBL"
SPDX-License-Identifier = "CC0-1.0"
