# SPDX-FileCopyrightText: 2024 DB Systel GmbH
# SPDX-License-Identifier: CC0-1.0

# A Team with its name
Project Team:
  # Description of the team
  description: "My awesome Maintainers team"
  # Level of privacy of the team. Can be "secret" or "closed". Note: parent/child teams cannot be "secret"
  privacy: "closed"
  # Notification setting of the team.
  # Can be "notifications_enabled" or "notifications_disabled"
  notification_setting: "notifications_enabled"
  # Team maintainers, can add new people and change team settings
  maintainer:
    - octocat
  # Normal team members
  member:
    - user1
    - user2
  # The repositories the team shall have access to with a certain permission
  # Can be one of: pull, triage, push, maintain, admin
  repos:
    cool-repository: push
    other-repo: push

Project Maintainers:
  # Make this a child team of the provided parent. Note: You should first
  # describe parents in this file, then children
  parent: Maintainers
  # Organisation roles that shall be assigned to this team. Any other
  # organisation roles of the team are removed. Predefined roles are:
  # all_repo_read, all_repo_triage, all_repo_write, all_repo_maintain,
  # all_repo_admin, app_manager, ci_cd_admin, security_manager,
  # open_source_license_manager
  roles:
    - app_manager
  member:
    - octocat
  repos:
    cool-repository: admin
    other-repo: maintain
