# SPDX-FileCopyrightText: 2024 DB Systel GmbH
# SPDX-License-Identifier: CC0-1.0

# A Team with its name
Maintainers:
  # Team maintainers, can add new people and change team settings
  maintainer:
    - octocat
  # Normal team members
  member:
    - user1
    - user2
  # The repositories the team shall have access to with a certain permission
  # Can be one of: pull, triage, push, maintain, admin
  repos:
    cool-repository: admin
    other-repo: admin

Subproject:
  parent: Maintainers
  member:
    - user2
  repos:
    cool-repository: maintain
