teams:
  # ----------------------------------------------------------------------------
  # General OpenRail teams
  # ----------------------------------------------------------------------------
  Technical Committee:
    members:
      - cornelius
      - Keller-Peter
      - loic-hamelin

  OpenRail Team:
    members:
      - cornelius
      - Keller-Peter
      - loic-hamelin
      - MahaliaStephan
      - mxmehl
      - SimonClavier
      - vlasceanuic
  # ----------------------------------------------------------------------------
  # OSRD - Open Source Railway Designer
  # ----------------------------------------------------------------------------
  OSRD:
    members:
      # Team Maintainers
      - bloussou
      - ElysaSrc
      - flomonster
      - loic-hamelin
      - nicolaswurtz
      # Normal members
      - achrafmohye
      - Akctarus
      - anisometropie
      - bougue-pe
      - Caracol3
      - cassandrafestoc
      - Castavo
      - celine-sncf
      - ConstanceDragibus
      - El-Youssef
      - estia-m
      - hamz2a
      - jacomyal
      - kmer2016
      - louisgreiner
      - maelysLeratRosso
      - manalzidani
      - Maymanaf
      - Morgane-SJK
      - RomainValls
      - SarahBellaha
      - SharglutDev
      - sim51
      - SimonPierreED
      - thibautsailly
      - Tristramg
      - Uriel-Sautron
      - Wadjetz
      - Yohh
  OSRD-Admins:
    parent: OSRD
    members:
      # Team Maintainers
      - flomonster
      - loic-hamelin
      # Normal members
      - bloussou
      - nicolaswurtz
  # All members in the OSRD Maintainers team and the subteams are team maintainers
  OSRD-Maintainers:
    parent: OSRD
    members:
      - loic-hamelin
  OSRD-DevOps:
    parent: OSRD Maintainers
    members:
      - bloussou
      - ElysaSrc
      - Khoyo
      - multun
      - younesschrifi
  OSRD-Core:
    parent: OSRD Maintainers
    members:
      - eckter
      - Erashin
      - Khoyo
      - multun
  OSRD-Editoast:
    parent: OSRD Maintainers
    members:
      - woshilapin
      - flomonster
      - Tguisnet
      - leovalais
  OSRD-Front:
    parent: OSRD Maintainers
    members:
      - clarani
      - Math-R
      - nicolaswurtz
      - SharglutDev
  OSRD-Tests:
    parent: OSRD Maintainers
    members:
      - bloussou
      - eckter
      - shenriotpro
  OSRD-Physics:
    parent: OSRD Maintainers
    members:
      - axrolld
      - bgiuliana
