teams:
  OSRD:
  OSRD Admins:
    parent: OSRD
    members:
      - loic-hamelin
  OSRD Maintainers:
    parent: OSRD
  OSRD Maintainers DevOps:
    parent: OSRD Maintainers
    members:
      - mmthrowawayacc
  OSRD Maintainers Core:
    parent: OSRD Maintainers
  OSRD Maintainers Editoast:
    parent: OSRD Maintainers
  OSRD Maintainers Front:
    parent: OSRD Maintainers
  OSRD Maintainers Tests:
    parent: OSRD Maintainers
  OSRD Maintainers Physics:
    parent: OSRD Maintainers
  foobar:
    members:
      - mxmehl
      - mmthrowawayacc
