teams:
  OSRD:
    Admins:
    Maintainers:
      DevOps:
      Core:
      Editoast:
      Front:
      Tests:
      Physics:

members:
  achrafmohye:
    teams:
      -
  Akctarus:
    teams:
      -
  anisometropie:
    teams:
      -
  axrolld:
    teams:
      -
  bgiuliana:
    teams:
      -
  bloussou:
    teams:
      -
  bougue-pe:
    teams:
      -
  Caracol3:
    teams:
      -
  cassandrafestoc:
    teams:
      -
  Castavo:
    teams:
      -
  clarani:
    teams:
      -
  eckter:
    teams:
      -
  ElysaSrc:
    teams:
      -
  Erashin:
    teams:
      -
  estia-m:
    teams:
      -
  flomonster:
    teams:
      -
  hamz2a:
    teams:
      -
  jacomyal:
    teams:
      -
  Khoyo:
    teams:
      -
  kmer2016:
    teams:
      -
  leovalais:
    teams:
      -
  loic-hamelin:
    teams:
      -
  louisgreiner:
    teams:
      -
  maelysLeratRosso:
    teams:
      -
  manalzidani:
    teams:
      -
  Math-R:
    teams:
      -
  Maymanaf:
    teams:
      -
  Morgane-SJK:
    teams:
      -
  multun:
    teams:
      -
  nicolaswurtz:
    teams:
      -
  Omar-938:
    teams:
      -
  SarahBellaha:
    teams:
      -
  SharglutDev:
    teams:
      -
  shenriotpro:
    teams:
      -
  sim51:
    teams:
      -
  SimonPierreED:
    teams:
      -
  Tguisnet:
    teams:
      -
  Tristramg:
    teams:
      -
  Uriel-Sautron:
    teams:
      -
  Wadjetz:
    teams:
      -
  woshilapin:
    teams:
      -
  Yohh:
    teams:
      -
  younesschrifi:
    teams:
      -
