# SPDX-FileCopyrightText: 2024 DB Systel GmbH
# SPDX-License-Identifier: CC0-1.0

# ------------------------------------------------------------------------------
# General configuration for this program
# ------------------------------------------------------------------------------

# Personal Oauth access token with required scopes
github_token: ghp_abcdefg123
