# SPDX-FileCopyrightText: 2024 DB Systel GmbH
# SPDX-License-Identifier: CC0-1.0

# ------------------------------------------------------------------------------
# General configuration for the GitHub organisation
# ------------------------------------------------------------------------------

# Name of the GitHub organisation
org_name: example-org-on-github
# List of owners of the GitHub organisation
org_owners:
  - octocat
