# ------------------------------------------------------------------------------
# General configuration for the GitHub organisation
# ------------------------------------------------------------------------------

# Name of the GitHub organisation
org_name: example-org-on-github
